In [15]:
import numpy as np

x = np.arange(4).reshape((2, 2))

In [16]:
x

array([[0, 1],
       [2, 3]])

In [17]:
# transpose在不指定参数是默认是矩阵转置
x.transpose()

array([[0, 2],
       [1, 3]])

In [18]:
# transpose指定参数
x.transpose((0, 1))

array([[0, 1],
       [2, 3]])