https://tensorflow.google.cn/api_docs/python/tf/linalg

In [1]:
import tensorflow as tf

In [2]:
# adjoint
# Transposes the last two dimensions of and conjugates tensor matrix.
# The adjoint (a.k.a. Hermitian transpose a.k.a. conjugate transpose) of matrix.
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
y=tf.linalg.adjoint(x)  
# [[1 - 1j, 4 - 4j],
#  [2 - 2j, 5 - 5j],
#  [3 - 3j, 6 - 6j]]
y

<tf.Tensor: id=2, shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

In [3]:
# band_part
x = tf.constant([[ 0,  1,  2, 3],
                 [-1,  0,  1, 2],
                 [-2, -1,  0, 1],
                 [-3, -2, -1, 0]])
tf.linalg.band_part(x, 1, -1)
# [[ 0,  1,  2, 3]
# [-1,  0,  1, 2]
# [ 0, -1,  0, 1]
# [ 0,  0, -1, 0]]
tf.linalg.band_part(x, 2, 1) 
# [[ 0,  1,  0, 0]
# [-1,  0,  1, 0]
# [-2, -1,  0, 1]
# [ 0, -2, -1, 0]]

<tf.Tensor: id=9, shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  0,  0],
       [-1,  0,  1,  0],
       [-2, -1,  0,  1],
       [ 0, -2, -1,  0]], dtype=int32)>

In [4]:
# Computes the Cholesky decomposition of one or more square matrices.
# 分解是把一个对称正定的矩阵表示成一个下三角矩阵L和其转置的乘积的分解。
# 它要求矩阵的所有特征值必须大于零，故分解的下三角的对角元也是大于零的。
# Cholesky分解法又称平方根法，是当A为实对称正定矩阵时，LU三角分解法的变形。
x = tf.constant([[ 0,  1,  2, 3],
                 [-1,  0,  1, 2],
                 [-2, -1,  0, 1],
                 [-3, -2, -1, 0]])
# tf.linalg.cholesky(x)

NotFoundError: Could not find valid device for node.
Node:{{node Cholesky}}
All kernels registered for op Cholesky :
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
 [Op:Cholesky]

In [6]:
# diag
# The main diagonal.
import numpy as np

diagonal = np.array([[1, 2, 3, 4],            # Input shape: (2, 4)
                     [5, 6, 7, 8]])
tf.linalg.diag(diagonal) 
# [[[1, 0, 0, 0],  # Output shape: (2, 4, 4)
# [0, 2, 0, 0],
# [0, 0, 3, 0],
# [0, 0, 0, 4]],
# [[5, 0, 0, 0],
# [0, 6, 0, 0],
# [0, 0, 7, 0],
# [0, 0, 0, 8]]]

# # A superdiagonal (per batch).
# diagonal = np.array([[1, 2, 3],  # Input shape: (2, 3)
#                      [4, 5, 6]])
# tf.matrix_diag(diagonal, k = 1)
#   ==> [[[0, 1, 0, 0],  # Output shape: (2, 4, 4)
#         [0, 0, 2, 0],
#         [0, 0, 0, 3],
#         [0, 0, 0, 0]],
#        [[0, 4, 0, 0],
#         [0, 0, 5, 0],
#         [0, 0, 0, 6],
#         [0, 0, 0, 0]]]

# # A band of diagonals.
# diagonals = np.array([[[1, 2, 3],  # Input shape: (2, 2, 3)
#                        [4, 5, 0]],
#                       [[6, 7, 9],
#                        [9, 1, 0]]])
# tf.matrix_diag(diagonals, k = (-1, 0))
#   ==> [[[1, 0, 0],  # Output shape: (2, 3, 3)
#         [4, 2, 0],
#         [0, 5, 3]],
#        [[6, 0, 0],
#         [9, 7, 0],
#         [0, 1, 9]]]

# # Rectangular matrix.
# diagonal = np.array([1, 2])  # Input shape: (2)
# tf.matrix_diag(diagonal, k = -1, num_rows = 3, num_cols = 4)
#   ==> [[0, 0, 0, 0],  # Output shape: (3, 4)
#        [1, 0, 0, 0],
#        [0, 2, 0, 0]]

# # Rectangular matrix with inferred num_cols and padding_value = 9.
# tf.matrix_diag(diagonal, k = -1, num_rows = 3, padding_value = 9)
#   ==> [[9, 9],  # Output shape: (3, 2)
#        [1, 9],
#        [9, 2]]

<tf.Tensor: id=12, shape=(2, 4, 4), dtype=int64, numpy=
array([[[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]],

       [[5, 0, 0, 0],
        [0, 6, 0, 0],
        [0, 0, 7, 0],
        [0, 0, 0, 8]]])>

# Classes

class LinearOperator: Base class defining a [batch of] linear operator[s].

class LinearOperatorAdjoint: LinearOperator representing the adjoint of another operator.

class LinearOperatorBlockDiag: Combines one or more LinearOperators in to a Block Diagonal matrix.

class LinearOperatorCirculant: LinearOperator acting like a circulant matrix.

class LinearOperatorCirculant2D: LinearOperator acting like a block circulant matrix.

class LinearOperatorCirculant3D: LinearOperator acting like a nested block circulant matrix.

class LinearOperatorComposition: Composes one or more LinearOperators.

class LinearOperatorDiag: LinearOperator acting like a [batch] square diagonal matrix.

class LinearOperatorFullMatrix: LinearOperator that wraps a [batch] matrix.

class LinearOperatorHouseholder: LinearOperator acting like a [batch] of Householder transformations.

class LinearOperatorIdentity: LinearOperator acting like a [batch] square identity matrix.

class LinearOperatorInversion: LinearOperator representing the inverse of another operator.

class LinearOperatorKronecker: Kronecker product between two LinearOperators.

class LinearOperatorLowRankUpdate: Perturb a LinearOperator with a rank K update.

class LinearOperatorLowerTriangular: LinearOperator acting like a [batch] square lower triangular matrix.

class LinearOperatorPermutation: LinearOperator acting like a [batch] of permutation matrices.

class LinearOperatorScaledIdentity: LinearOperator acting like a scaled [batch] identity matrix A = c I.

class LinearOperatorToeplitz: LinearOperator acting like a [batch] of toeplitz matrices.

class LinearOperatorZeros: LinearOperator acting like a [batch] zero matrix.

# Functions

adjoint(...): Transposes the last two dimensions of and conjugates tensor matrix.

band_part(...): Copy a tensor setting everything outside a central band in each innermost matrix

cholesky(...): Computes the Cholesky decomposition of one or more square matrices.

cholesky_solve(...): Solves systems of linear eqns A X = RHS, given Cholesky factorizations.

cross(...): Compute the pairwise cross product.

det(...): Computes the determinant of one or more square matrices.

diag(...): Returns a batched diagonal tensor with given batched diagonal values.

diag_part(...): Returns the batched diagonal part of a batched tensor.

eig(...): Computes the eigen decomposition of a batch of matrices.

eigh(...): Computes the eigen decomposition of a batch of self-adjoint matrices.

eigvals(...): Computes the eigenvalues of one or more matrices.

eigvalsh(...): Computes the eigenvalues of one or more self-adjoint matrices.

einsum(...): Tensor contraction over specified indices and outer product.

expm(...): Computes the matrix exponential of one or more square matrices.

eye(...): Construct an identity matrix, or a batch of matrices.

global_norm(...): Computes the global norm of multiple tensors.

inv(...): Computes the inverse of one or more square invertible matrices or their

l2_normalize(...): Normalizes along dimension axis using an L2 norm.

logdet(...): Computes log of the determinant of a hermitian positive definite matrix.

logm(...): Computes the matrix logarithm of one or more square matrices:

lstsq(...): Solves one or more linear least-squares problems.

lu(...): Computes the LU decomposition of one or more square matrices.

lu_matrix_inverse(...): Computes the inverse given the LU decomposition(s) of one or more matrices.

lu_reconstruct(...): The reconstruct one or more matrices from their LU decomposition(s).

lu_solve(...): Solves systems of linear eqns A X = RHS, given LU factorizations.

matmul(...): Multiplies matrix a by matrix b, producing a * b.

matrix_rank(...): Compute the matrix rank of one or more matrices.

matrix_transpose(...): Transposes last two dimensions of tensor a.

matvec(...): Multiplies matrix a by vector b, producing a * b.

norm(...): Computes the norm of vectors, matrices, and tensors.

normalize(...): Normalizes tensor along dimension axis using specified norm.

pinv(...): Compute the Moore-Penrose pseudo-inverse of one or more matrices.

qr(...): Computes the QR decompositions of one or more matrices.

set_diag(...): Returns a batched matrix tensor with new batched diagonal values.

slogdet(...): Computes the sign and the log of the absolute value of the determinant of

solve(...): Solves systems of linear equations.

sqrtm(...): Computes the matrix square root of one or more square matrices:

svd(...): Computes the singular value decompositions of one or more matrices.

tensor_diag(...): Returns a diagonal tensor with a given diagonal values.

tensor_diag_part(...): Returns the diagonal part of the tensor.

tensordot(...): Tensor contraction of a and b along specified axes and outer product.

trace(...): Compute the trace of a tensor x.

triangular_solve(...): Solves systems of linear equations with upper or lower triangular matrices by backsubstitution.

tridiagonal_matmul(...): Multiplies tridiagonal matrix by matrix.

tridiagonal_solve(...): Solves tridiagonal systems of equations.